<?php

/*
 *    _____               _   _
 *   |  __ \             | | (_)
 *   | |__) | __ ___  ___| |_ _  __ _  ___
 *   |  ___/ '__/ _ \/ __| __| |/ _` |/ _ \
 *   | |   | | |  __/\__ \ |_| | (_| |  __/
 *   |_|   |_|  \___||___/\__|_|\__, |\___|
 *                               __/ |
 *                              |___/
 *    Make by ThinkerS
 */

namespace ThinkerS\Prestige;

use pocketmine\plugin\PluginBase;

class Loader extends PluginBase
{
    public static $instance;

    public function onEnable()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    /*
    *              _____ _____
    *        /\   |  __ \_   _|
    *       /  \  | |__) || |
    *      / /\ \ |  ___/ | |
    *     / ____ \| |    _| |_
    *    /_/    \_\_|   |_____|
    *
    */

    public function onLoad()
    {
        self::$instance = $this;
    }

    public function getInstance(): Loader
    {
        return $this;
    }
}