api-key: "jAyD7QfRsg58LkOSmhpTtIjogdXT7yPLr2l" # API Key from https://minecraftpocket-servers.com/servers/manage/.
commands:
    # Commands to be executed when a player claims their vote.
    # They should not include the first "/" and they should be encased in quotes.
    # It is recommended to encase the username variable in escaped quotes (\") to make sure it
    #  is sent as one argument to the command to ensure they get all of their rewards.
    # List of useable variables:
    #  {username}: The player's in game username
    #  {displayname}: The player's display/nick name
    #  {x}: The player's X coordinate
    #  {y}: The player's Y coordinate
    #  {z}: The player's Z coordinate
    - "say {username} haz vote for server and earn a COOOL reward!"
    - "title \"{username}\" title &aThank for your voting !"
    - "coin add {username} 2"
    - "addmoney {username} 200"
# If droprewards is true, rewards will be dropped on the floor if a player's inventory is full
# If droprewards if false, rewards will dissapear if a player's inventory is full
droprewards: false
items:
    # Items to be given to a player when they claim their vote.
    # They should follow the format: "item_name:meta:amount:name:enchant_name:enchant_level".
    #  "name" can either be a custom name, or "default" to have no custom name.
    #  "item_name", "meta", "amount" & "name" must all come before any enchantments.
    #  "enchant_name:enchant_level" can be repeated as many times as you want.
    # Enchantments from PiggyCustomEnchants are also supported, use them the same as regular enchants.
    # They should also always be encased in quotes to make sure they get parsed properly.
    - "stone:0:0"
    #- "steak:0:64:Porkchops"
    #- "diamond_sword:0:1:&lPowerful Sword:sharpness:5:unbreaking:3"
    #- "bow:0:1:&dPiggy's Bow:power:5:unbreaking:3:porkified:3"
messages:
    info:
        title: "&aThis server's vote information:"
        content: "&aUptime: {uptime}\n&aScore: {score}\n&aRank: {rank}\n&aVotes: {votes}\n&aFavorited: {favorited}\n&aComments: {comments}"
    noperms: "&cYou do not have permission to use this command."
    reload:
        success: "&aYou have reloaded the server's vote configuration."
    top:
        novoters: "&cThere are no top voters."
        title: "&aTop voters this month:"
        format: "&a{place}. {username}: {votes}"
    vote:
        alreadyclaimed: "&cYou have already claimed your vote."
        alreadyprocessing: "&cYour vote is already being processed."
        claimed: "&aThank you for voting! You have received your rewards."
        error: "&cUnable to claim your vote, please try again later."
        notvoted: "&cYou have not voted yet."
        processing: "&aYour vote is being processed, please wait."
        usage:
            notplayer: "&cUse '/vote <info|reload|top>'."
            other: "&cUse '/vote [info|top]."
            reloadperm: "&cUse '/vote [info|reload|top]."