<?php

namespace NgLamVN\FartBattle;

use pocketmine\block\Block;
use pocketmine\block\Furnace;
use pocketmine\entity\projectile\Arrow;
use pocketmine\item\Item;
use pocketmine\math\RayTraceResult;

class WeirdArrow extends Arrow
{
    public function onHitBlock(Block $blockHit, RayTraceResult $hitResult): void
    {
        parent::onHitBlock($blockHit, $hitResult); // TODO: Change the autogenerated stub

        if ($blockHit instanceof Furnace)
        {
            if ($this->isOnFire())
            {
                $title = $blockHit->getLevelNonNull()->getTile($blockHit->asVector3());

                if ($title instanceof \pocketmine\tile\Furnace)
                {
                    $title->getInventory()->setFuel(Item::get(Item::COAL));
                }
            }
        }
    }
}