---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: false
  message: "&e[{TIME}] &aWelcome to your server! &n&b[{TOTALPLAYERS}/{MAXPLAYERS}]"
OutdatedClient:
  custom: true
  message: "&cPlease use MCBE version 1.16.220+!"
OutdatedServer:
  custom: true
  message: "&cOops! Server outdated!"
WhitelistedServer:
  custom: true
  message: "&c&oThis Server is in maintenance mode!"
FullServer:
  custom: true
  message: "&eThe Server is full &b!\n&l&dTry to join later :)"
FirstJoin:
  enable: true
  message: "&e[&dNew&e] &b{PLAYER}"
Join:
  hide: false
  custom: true
  message: "&e[&a+&e] &b{PLAYER}"
Quit:
  hide: false
  custom: true
  message: "&e[&c-&e] &b{PLAYER}"
WorldChange:
  enable: false
  message: "&2[{TIME}] &a{PLAYER}&e moved from &c{ORIGIN}&e to &a{TARGET}"
Death:
  hide: false
  custom: true
  message: "&7{PLAYER} died"
  death-contact-message:
    hide: false
    custom: true
    message: "&eOops! {PLAYER} was killed by {BLOCK}"
  kill-message:
    hide: false
    custom: true
    message: "&e{PLAYER} &ewas killed by &c{KILLER}"
  death-projectile-message:
    hide: false
    custom: true
    message: "&e{PLAYER} was killed by {KILLER} by arrow"
  death-suffocation-message:
    hide: false
    custom: true
    message: "&c{PLAYER} suffocated"
  death-fall-message:
    hide: false
    custom: true
    message: "&7{PLAYER} fell from a high place"
  death-fire-message:
    hide: false
    custom: true
    message: "&6{PLAYER} went up in flames"
  death-on-fire-message:
    hide: false
    custom: true
    message: "&6{PLAYER} burned"
  death-lava-message:
    hide: false
    custom: true
    message: "&6{PLAYER} tried to swim in lava"
  death-drowning-message:
    hide: false
    custom: true
    message: "&b{PLAYER} drowned"
  death-explosion-message:
    hide: false
    custom: true
    message: "&c{PLAYER} exploded"
  death-void-message:
    hide: false
    custom: true
    message: "&7{PLAYER} went to space"
  death-suicide-message:
    hide: false
    custom: true
    message: "&7{PLAYER} committed suicide"
  death-magic-message:
    hide: false
    custom: true
    message: "&a{PLAYER} was killed by a spell"
...
