<?php

namespace NgLamVN\FIScore;

use Ifera\ScoreHud\event\PlayerTagUpdateEvent;
use pocketmine\plugin\PluginBase;
use Ifera\ScoreHud\scoreboard\ScoreTag;
use pocketmine\scheduler\ClosureTask;
use pocketmine\utils\TextFormat;

class Loader extends PluginBase
{
    public function onEnable()
    {
        $task = new ClosureTask(function (int $_): void
        {
            foreach ($this->getServer()->getOnlinePlayers() as $player)
            {
                $ping = $player->getPing();
                if ($ping < 80) $color = "§a";
                elseif ($ping < 150) $color = "§e";
                elseif ($ping < 200) $color = "§6";
                else $color = "§c";
                
                (new PlayerTagUpdateEvent($player, new ScoreTag("fi-scoreloader.ping",$color . $player->getPing())))->call();
            }
        });
        $this->getScheduler()->scheduleRepeatingTask($task, 5*20);

        $this->getServer()->getPluginManager()->registerEvents(new EventListener(), $this);
        $this->getServer()->getPluginManager()->registerEvents(new TagResloveListener(), $this);
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}
